### ISSUE TITLE
Gmail联系人

### ISSUE THREAD

**Issue by Mindzy** [iAugux/Phonetic#2]
第一时间买了苹果appstore上的版本，相当好用。现在iphone上已经搞定
但由于苹果通讯录与gmail在Phonetic这项上无法同步，能有什么办法在gmail上实现注音嘛？十分感谢！

**Comment by iAugux** [comment]
@dzy92 感谢支持！回头我研究一下，不过不要报太大希望，我感觉应该无法实现。因为gmail和iOS上都要考虑，而且iOS比较封闭，不允许添加自定义的字段

**Comment by iAugux** [comment]
@dzy92 我测试了一下，不管是在 Google上新建的联系人还是在 iCloud 上新建的，双向同步都没有问题啊！Phonetic 字段没有丢失

**Comment by Mindzy** [comment]
感谢您的回复！
在我的实际使用中，gmail上编辑的Phonetic可以同步到iphone，但在iphone上编辑的Phonetic无法同步到gmail。不知道我是不是个例。

**Comment by iAugux** [comment]
@dzy92 你手机上通讯录默认账户是 iCloud 吧？你在iPhone上新添加的联系人存储在 iCloud 上，而不是 Google 账户上，所以无法同步到 Google Contacts 上， Mail, Contacts, Calendars -> (Contacts) Default Account -> 选择你的 Google 账户

**Comment by Mindzy** [comment]
不是的，我没有用icloud，所有的联系人都是google contacts上同步过来的。而且我只使用google contacts，使用的是Mail, Contacts, Calendars下的google的账户。所以也没有找到Mail, Contacts, Calendars -> (Contacts) Default Account这个选项。
除了Phonetic，在iphone上对联系人的任何修改都可以在web gmail上的google contacts看到。
iOS系统是9.3.1。

**Comment by iAugux** [comment]
Phonetic 添加的字段和你手动添加的字段没有区别的，只是批量帮你添加了

**Comment by iAugux** [comment]
不好意思，理解错了，我以为你说的 Phonetic 指的是我的软件

**Comment by iAugux** [comment]
好奇怪，我今天测试了，是可以同步的。难道是因为我同时设置了 iCloud 账户吗

**Comment by Mindzy** [comment]
是有方法能让icloud跟google contacts关联吗？

**Comment by iAugux** [comment]
我正在测试，你用什么即时聊天，我加你，方便点

**Comment by Mindzy** [comment]
微信吧，微信号发到我邮箱吧，dzy92@163.com，十分感谢！

**Comment by duhd1993** [comment]
冒昧问一下，这个问题后来发现原因了么？我的情况很类似，我的所有联系人都是通过Google同步来的，iCloud没有开。通过Phonetic添加注音后，注音无法同步到Google，反而有部分人的注音被消除了；昵称可以同步，但只有注音被消除的那些人的昵称被同步到了Google。但在Google做任何改动都能正确同步到手机上。现在只有两个选择，一个是使用iCloud同步，另外就是每次添加人都通过Google。

**Comment by g6ai** [comment]
> 

我和你的情况相同。

**Comment by g6ai** [comment]
> 冒昧问一下，这个问题后来发现原因了么？我的情况很类似，我的所有联系人都是通过Google同步来的，iCloud没有开。通过Phonetic添加注音后，注音无法同步到Google，反而有部分人的注音被消除了；昵称可以同步，但只有注音被消除的那些人的昵称被同步到了Google。但在Google做任何改动都能正确同步到手机上。现在只有两个选择，一个是使用iCloud同步，另外就是每次添加人都通过Google。

我和你的情况相同
