### ISSUE TITLE
[Suggestion] Difficulty figuring out how to clear existing information

### ISSUE THREAD

**Issue by mogita** [iAugux/Phonetic#3]
I'm a user from the App Store.

I added phonetic information to all of my contacts, then realized all nicknames were turning into abbrs, making my message list hard to read, since contacts' names are abbrs instead of full name. 

So I decided to use Notes field for quick search, and toggled on "clean nickname key" and then processed all contacts. While quick search was indeed added to the Notes field, the nickname fields were left intact.

I tried several times and then figured out, I have to do an explicit "clear" process (long tap or double tap) to clear the nickname field, even though I've toggle on "clean nickname key". To my understanding, what I configured in the settings should take effect at once, as in one click on the "finger print button", not expecting that all settings are actually separated into two kinds of operations on the UI, even though a line of text is there trying to explain this. A bulk tool usually makes all pre-defined process in one pass.

So my suggestion is, all settings are taking effect at the same time, and the "finger print button" should behave idempotently, meanwhile displaying what's gonna happen when the user taps it, instead of "Tap to add phonetic keys, double tap or long press to clean", which is not so helpful if it stays there and never changes.

Thank you for reading it through, and offering this handy app. Great work!

**Comment by iAugux** [comment]
@mogita Thanks for your feedback!

_**`So my suggestion is, all settings are taking effect at the same time`**_

What you suggested looks more convenient to users, but this will take more time to proceed each time.
Adding phonetic is used more often than removing, so i think the speed is more important.

Thanks again!

**Comment by mogita** [comment]
Thanks! I got your idea.

How about splitting "Adding" and "Clearing" into two presentational parts? Like two buttons?

**Comment by iAugux** [comment]
Emmmm, how often do you use the clearing action? 😆 
 I don’t think it is necessary.  Besides, Phonetic supports 3D Touch shortcuts

**Comment by mogita** [comment]
Well, fair enough xD

I do a Phonetic once a contact is added and clearing even less, so not quite often. Actually once learned, the way to use it doesn't bother me at all. It's not the implementation itself that makes things a little bit of trickier. It was some confusion that the first-time users might get.

Sorry that I'm not capable of drawing you a design, but I'm still thankful for your attention to what I was thinking. 😊

**Comment by iAugux** [comment]
Thank you!
