### ISSUE TITLE
无法清除URL字段

### ISSUE THREAD

**Issue by LuzMasonj** [iAugux/Phonetic#5]
之前不知道用过哪个网络电话 自动在每个联系人里加了一条URL字段 Phonetics 还不支持清除 能增加下URL支持吗
![c83cb255-924f-4c64-8f03-2fd1690b161c](https://user-images.githubusercontent.com/27768847/51797440-a3076b80-223e-11e9-9b8d-b2b59b39c3c9.png)

**Comment by iAugux** [comment]
不好意思！请联系「网络电话」的作者协助清理。
