### ISSUE TITLE
“谌”姓应读为Shèn

### ISSUE THREAD

**Issue by lukaschan** [iAugux/Phonetic#7]
如题，非chen，而应是Shèn

**Comment by lukaschan** [comment]
发现不能自定义增添多音字，是没这个功能吧。。。

**Comment by iAugux** [comment]
> 如题，非chen，而应是Shèn

应该是都可以 https://baike.baidu.com/item/谌姓/4883494

**Comment by iAugux** [comment]
> 发现不能自定义增添多音字，是没这个功能吧。。。

没有：）

**Comment by iAugux** [comment]
> > 如题，非chen，而应是Shèn
> 
> 应该是都可以 [https://baike.baidu.com/item/谌姓/4883494](https://baike.baidu.com/item/%E8%B0%8C%E5%A7%93/4883494)

如果要自定义的话，可以加到白名单中然后自定义
